steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/cover-letter-api:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/cover-letter-api:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "cover-letter-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/cover-letter-api:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
      - "--memory"
      - "512Mi"
      - "--timeout"
      - "300"
      - "--max-instances"
      - "10"

images:
  - "gcr.io/$PROJECT_ID/cover-letter-api:$COMMIT_SHA"
