services:
  - type: web
    name: cover-letter-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false # You'll set this manually in Render dashboard
